/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as RiffRouteImport } from './routes/riff'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'

const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const RiffRoute = RiffRouteImport.update({
  id: '/riff',
  path: '/riff',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launch': typeof LaunchRoute
  '/riff': typeof RiffRoute
  '/scenes': typeof ScenesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launch': typeof LaunchRoute
  '/riff': typeof RiffRoute
  '/scenes': typeof ScenesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launch': typeof LaunchRoute
  '/riff': typeof RiffRoute
  '/scenes': typeof ScenesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/how-it-works' | '/launch' | '/riff' | '/scenes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/how-it-works' | '/launch' | '/riff' | '/scenes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/how-it-works'
    | '/launch'
    | '/riff'
    | '/scenes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LaunchRoute: typeof LaunchRoute
  RiffRoute: typeof RiffRoute
  ScenesRoute: typeof ScenesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riff': {
      id: '/riff'
      path: '/riff'
      fullPath: '/riff'
      preLoaderRoute: typeof RiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  HowItWorksRoute: HowItWorksRoute,
  LaunchRoute: LaunchRoute,
  RiffRoute: RiffRoute,
  ScenesRoute: ScenesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
